---
#- name: Install required packages for Clevis
#  yum:
#    name: "{{ clevis_packages }}"
#    state: latest

#- name: Copy template for Dracut config
#  template:
#    src: etc_dracut_conf_d_static_ip.j2
#    dest: /etc/dracut.conf.d/static_ip.conf
#    owner: root
#    group: root
#    mode: 0644
#  notify: rebuild initramfs

- name: Check for whether you're on an EFI system
  stat:
    path: /sys/firmware/efi
  register: EFI

#- name: Install FIPS packages
#  yum:
#    name: "{{ fips_packages }}"
#    state: latest
#  notify: rebuild initramfs

- name: Set boot paramaters if EFI system
  block:
    - name: Set boot filesystem
      set_fact:
        bootfs: /boot/efi

    - name: Set boot filesystem
      set_fact:
        grub: /boot/efi/EFI/redhat/grub.cfg
  when: EFI.stat.exists
  
- name: Get UUID of boot partition
  command: "findmnt --noheadings --output uuid --target {{ bootfs }}"
  register: bootuuid

- name: Copy over a sane /etc/default/grub
  template:
    src: etc_default_grub.j2
    dest: /etc/default/grub
    owner: root
    group: root
    mode: 0644
  

